CREATE FUNCTION [dbo].[MacRoman2Unicode](@string varchar(max)) RETURNS nvarchar(max) AS
BEGIN
    DECLARE @result nvarchar(max)
    DECLARE @index int
    DECLARE @char char
    
    IF @string IS NULL RETURN NULL
    
    SET @index = 1
    SET @result = N''
    WHILE @index <= LEN(@string)
    BEGIN
        SET @char = SUBSTRING(@string, @index, 1)
        SET @result = @result + CASE ASCII(@char)
            WHEN 0x80 THEN NCHAR(0x00c4) -- LATIN CAPITAL LETTER A WITH DIAERESIS
            WHEN 0x81 THEN NCHAR(0x00c5) -- LATIN CAPITAL LETTER A WITH RING ABOVE
            WHEN 0x82 THEN NCHAR(0x00c7) -- LATIN CAPITAL LETTER C WITH CEDILLA
            WHEN 0x83 THEN NCHAR(0x00c9) -- LATIN CAPITAL LETTER E WITH ACUTE
            WHEN 0x84 THEN NCHAR(0x00d1) -- LATIN CAPITAL LETTER N WITH TILDE
            WHEN 0x85 THEN NCHAR(0x00d6) -- LATIN CAPITAL LETTER O WITH DIAERESIS
            WHEN 0x86 THEN NCHAR(0x00dc) -- LATIN CAPITAL LETTER U WITH DIAERESIS
            WHEN 0x87 THEN NCHAR(0x00e1) -- LATIN SMALL LETTER A WITH ACUTE
            WHEN 0x88 THEN NCHAR(0x00e0) -- LATIN SMALL LETTER A WITH GRAVE
            WHEN 0x89 THEN NCHAR(0x00e2) -- LATIN SMALL LETTER A WITH CIRCUMFLEX
            WHEN 0x8a THEN NCHAR(0x00e4) -- LATIN SMALL LETTER A WITH DIAERESIS
            WHEN 0x8b THEN NCHAR(0x00e3) -- LATIN SMALL LETTER A WITH TILDE
            WHEN 0x8c THEN NCHAR(0x00e5) -- LATIN SMALL LETTER A WITH RING ABOVE
            WHEN 0x8d THEN NCHAR(0x00e7) -- LATIN SMALL LETTER C WITH CEDILLA
            WHEN 0x8e THEN NCHAR(0x00e9) -- LATIN SMALL LETTER E WITH ACUTE
            WHEN 0x8f THEN NCHAR(0x00e8) -- LATIN SMALL LETTER E WITH GRAVE
            WHEN 0x90 THEN NCHAR(0x00ea) -- LATIN SMALL LETTER E WITH CIRCUMFLEX
            WHEN 0x91 THEN NCHAR(0x00eb) -- LATIN SMALL LETTER E WITH DIAERESIS
            WHEN 0x92 THEN NCHAR(0x00ed) -- LATIN SMALL LETTER I WITH ACUTE
            WHEN 0x93 THEN NCHAR(0x00ec) -- LATIN SMALL LETTER I WITH GRAVE
            WHEN 0x94 THEN NCHAR(0x00ee) -- LATIN SMALL LETTER I WITH CIRCUMFLEX
            WHEN 0x95 THEN NCHAR(0x00ef) -- LATIN SMALL LETTER I WITH DIAERESIS
            WHEN 0x96 THEN NCHAR(0x00f1) -- LATIN SMALL LETTER N WITH TILDE
            WHEN 0x97 THEN NCHAR(0x00f3) -- LATIN SMALL LETTER O WITH ACUTE
            WHEN 0x98 THEN NCHAR(0x00f2) -- LATIN SMALL LETTER O WITH GRAVE
            WHEN 0x99 THEN NCHAR(0x00f4) -- LATIN SMALL LETTER O WITH CIRCUMFLEX
            WHEN 0x9a THEN NCHAR(0x00f6) -- LATIN SMALL LETTER O WITH DIAERESIS
            WHEN 0x9b THEN NCHAR(0x00f5) -- LATIN SMALL LETTER O WITH TILDE
            WHEN 0x9c THEN NCHAR(0x00fa) -- LATIN SMALL LETTER U WITH ACUTE
            WHEN 0x9d THEN NCHAR(0x00f9) -- LATIN SMALL LETTER U WITH GRAVE
            WHEN 0x9e THEN NCHAR(0x00fb) -- LATIN SMALL LETTER U WITH CIRCUMFLEX
            WHEN 0x9f THEN NCHAR(0x00fc) -- LATIN SMALL LETTER U WITH DIAERESIS
            WHEN 0xa0 THEN NCHAR(0x2020) -- DAGGER
            WHEN 0xa1 THEN NCHAR(0x00b0) -- DEGREE SIGN
            WHEN 0xa4 THEN NCHAR(0x00a7) -- SECTION SIGN
            WHEN 0xa5 THEN NCHAR(0x2022) -- BULLET
            WHEN 0xa6 THEN NCHAR(0x00b6) -- PILCROW SIGN
            WHEN 0xa7 THEN NCHAR(0x00df) -- LATIN SMALL LETTER SHARP S
            WHEN 0xa8 THEN NCHAR(0x00ae) -- REGISTERED SIGN
            WHEN 0xaa THEN NCHAR(0x2122) -- TRADE MARK SIGN
            WHEN 0xab THEN NCHAR(0x00b4) -- ACUTE ACCENT
            WHEN 0xac THEN NCHAR(0x00a8) -- DIAERESIS
            WHEN 0xad THEN NCHAR(0x2260) -- NOT EQUAL TO
            WHEN 0xae THEN NCHAR(0x00c6) -- LATIN CAPITAL LIGATURE AE
            WHEN 0xaf THEN NCHAR(0x00d8) -- LATIN CAPITAL LETTER O WITH STROKE
            WHEN 0xb0 THEN NCHAR(0x221e) -- INFINITY
            WHEN 0xb2 THEN NCHAR(0x2264) -- LESS-THAN OR EQUAL TO
            WHEN 0xb3 THEN NCHAR(0x2265) -- GREATER-THAN OR EQUAL TO
            WHEN 0xb4 THEN NCHAR(0x00a5) -- YEN SIGN
            WHEN 0xb6 THEN NCHAR(0x2202) -- PARTIAL DIFFERENTIAL
            WHEN 0xb7 THEN NCHAR(0x2211) -- N-ARY SUMMATION
            WHEN 0xb8 THEN NCHAR(0x220f) -- N-ARY PRODUCT
            WHEN 0xb9 THEN NCHAR(0x03c0) -- GREEK SMALL LETTER PI
            WHEN 0xba THEN NCHAR(0x222b) -- INTEGRAL
            WHEN 0xbb THEN NCHAR(0x00aa) -- FEMININE ORDINAL INDICATOR
            WHEN 0xbc THEN NCHAR(0x00ba) -- MASCULINE ORDINAL INDICATOR
            WHEN 0xbd THEN NCHAR(0x2126) -- OHM SIGN
            WHEN 0xbe THEN NCHAR(0x00e6) -- LATIN SMALL LIGATURE AE
            WHEN 0xbf THEN NCHAR(0x00f8) -- LATIN SMALL LETTER O WITH STROKE
            WHEN 0xc0 THEN NCHAR(0x00bf) -- INVERTED QUESTION MARK
            WHEN 0xc1 THEN NCHAR(0x00a1) -- INVERTED EXCLAMATION MARK
            WHEN 0xc2 THEN NCHAR(0x00ac) -- NOT SIGN
            WHEN 0xc3 THEN NCHAR(0x221a) -- SQUARE ROOT
            WHEN 0xc4 THEN NCHAR(0x0192) -- LATIN SMALL LETTER F WITH HOOK
            WHEN 0xc5 THEN NCHAR(0x2248) -- ALMOST EQUAL TO
            WHEN 0xc6 THEN NCHAR(0x2206) -- INCREMENT
            WHEN 0xc7 THEN NCHAR(0x00ab) -- LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
            WHEN 0xc8 THEN NCHAR(0x00bb) -- RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
            WHEN 0xc9 THEN NCHAR(0x2026) -- HORIZONTAL ELLIPSIS
            WHEN 0xca THEN NCHAR(0x00a0) -- NO-BREAK SPACE
            WHEN 0xcb THEN NCHAR(0x00c0) -- LATIN CAPITAL LETTER A WITH GRAVE
            WHEN 0xcc THEN NCHAR(0x00c3) -- LATIN CAPITAL LETTER A WITH TILDE
            WHEN 0xcd THEN NCHAR(0x00d5) -- LATIN CAPITAL LETTER O WITH TILDE
            WHEN 0xce THEN NCHAR(0x0152) -- LATIN CAPITAL LIGATURE OE
            WHEN 0xcf THEN NCHAR(0x0153) -- LATIN SMALL LIGATURE OE
            WHEN 0xd0 THEN NCHAR(0x2013) -- EN DASH
            WHEN 0xd1 THEN NCHAR(0x2014) -- EM DASH
            WHEN 0xd2 THEN NCHAR(0x201c) -- LEFT DOUBLE QUOTATION MARK
            WHEN 0xd3 THEN NCHAR(0x201d) -- RIGHT DOUBLE QUOTATION MARK
            WHEN 0xd4 THEN NCHAR(0x2018) -- LEFT SINGLE QUOTATION MARK
            WHEN 0xd5 THEN NCHAR(0x2019) -- RIGHT SINGLE QUOTATION MARK
            WHEN 0xd6 THEN NCHAR(0x00f7) -- DIVISION SIGN
            WHEN 0xd7 THEN NCHAR(0x25ca) -- LOZENGE
            WHEN 0xd8 THEN NCHAR(0x00ff) -- LATIN SMALL LETTER Y WITH DIAERESIS
            WHEN 0xd9 THEN NCHAR(0x0178) -- LATIN CAPITAL LETTER Y WITH DIAERESIS
            WHEN 0xda THEN NCHAR(0x2044) -- FRACTION SLASH
            WHEN 0xdb THEN NCHAR(0x00a4) -- CURRENCY SIGN
            WHEN 0xdc THEN NCHAR(0x2039) -- SINGLE LEFT-POINTING ANGLE QUOTATION MARK
            WHEN 0xdd THEN NCHAR(0x203a) -- SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
            WHEN 0xde THEN NCHAR(0xfb01) -- LATIN SMALL LIGATURE FI
            WHEN 0xdf THEN NCHAR(0xfb02) -- LATIN SMALL LIGATURE FL
            WHEN 0xe0 THEN NCHAR(0x2021) -- DOUBLE DAGGER
            WHEN 0xe1 THEN NCHAR(0x00b7) -- MIDDLE DOT
            WHEN 0xe2 THEN NCHAR(0x201a) -- SINGLE LOW-9 QUOTATION MARK
            WHEN 0xe3 THEN NCHAR(0x201e) -- DOUBLE LOW-9 QUOTATION MARK
            WHEN 0xe4 THEN NCHAR(0x2030) -- PER MILLE SIGN
            WHEN 0xe5 THEN NCHAR(0x00c2) -- LATIN CAPITAL LETTER A WITH CIRCUMFLEX
            WHEN 0xe6 THEN NCHAR(0x00ca) -- LATIN CAPITAL LETTER E WITH CIRCUMFLEX
            WHEN 0xe7 THEN NCHAR(0x00c1) -- LATIN CAPITAL LETTER A WITH ACUTE
            WHEN 0xe8 THEN NCHAR(0x00cb) -- LATIN CAPITAL LETTER E WITH DIAERESIS
            WHEN 0xe9 THEN NCHAR(0x00c8) -- LATIN CAPITAL LETTER E WITH GRAVE
            WHEN 0xea THEN NCHAR(0x00cd) -- LATIN CAPITAL LETTER I WITH ACUTE
            WHEN 0xeb THEN NCHAR(0x00ce) -- LATIN CAPITAL LETTER I WITH CIRCUMFLEX
            WHEN 0xec THEN NCHAR(0x00cf) -- LATIN CAPITAL LETTER I WITH DIAERESIS
            WHEN 0xed THEN NCHAR(0x00cc) -- LATIN CAPITAL LETTER I WITH GRAVE
            WHEN 0xee THEN NCHAR(0x00d3) -- LATIN CAPITAL LETTER O WITH ACUTE
            WHEN 0xef THEN NCHAR(0x00d4) -- LATIN CAPITAL LETTER O WITH CIRCUMFLEX
            WHEN 0xf1 THEN NCHAR(0x00d2) -- LATIN CAPITAL LETTER O WITH GRAVE
            WHEN 0xf2 THEN NCHAR(0x00da) -- LATIN CAPITAL LETTER U WITH ACUTE
            WHEN 0xf3 THEN NCHAR(0x00db) -- LATIN CAPITAL LETTER U WITH CIRCUMFLEX
            WHEN 0xf4 THEN NCHAR(0x00d9) -- LATIN CAPITAL LETTER U WITH GRAVE
            WHEN 0xf5 THEN NCHAR(0x0131) -- LATIN SMALL LETTER DOTLESS I
            WHEN 0xf6 THEN NCHAR(0x02c6) -- MODIFIER LETTER CIRCUMFLEX ACCENT
            WHEN 0xf7 THEN NCHAR(0x02dc) -- SMALL TILDE
            WHEN 0xf8 THEN NCHAR(0x00af) -- MACRON
            WHEN 0xf9 THEN NCHAR(0x02d8) -- BREVE
            WHEN 0xfa THEN NCHAR(0x02d9) -- DOT ABOVE
            WHEN 0xfb THEN NCHAR(0x02da) -- RING ABOVE
            WHEN 0xfc THEN NCHAR(0x00b8) -- CEDILLA
            WHEN 0xfd THEN NCHAR(0x02dd) -- DOUBLE ACUTE ACCENT
            WHEN 0xfe THEN NCHAR(0x02db) -- OGONEK
            WHEN 0xff THEN NCHAR(0x02c7) -- CARON
            ELSE @char
        END
        SET @index = @index + 1
    END
    
    RETURN @result
END

CREATE USER [calendars] FOR LOGIN [Calendars] WITH DEFAULT_SCHEMA=[dbo]
GRANT SELECT ON [dbo].[LGPEINAUS] TO [calendars]
GRANT SELECT ON [dbo].[LGPER] TO [calendars]
GRANT EXECUTE ON [dbo].[MacRoman2Unicode] TO [calendars]
